### ISSUE TITLE
Tests are broken with the puppet-rpec master branch

### ISSUE THREAD

**Issue by simonpasquier** [bfraser/puppet-grafana#46]
I'm looking at fixing issue #45 but I can't get the tests to pass on the master branch and the Travis CI is in the same state: 3 that_comes_before() assertions are failing. For instance:

```
Failures:

  1) grafana package install method debian use wget to fetch the package to a temporary location should contain Wget::Fetch[grafana] that comes before Package[grafana]
     Failure/Error: it { should contain_wget__fetch('grafana').that_comes_before('Package[grafana]') }
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:253:in `relationship_refs'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:264:in `block (2 levels) in relationship_refs'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:261:in `each'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:261:in `block in relationship_refs'
     # /var/lib/gems/1.9.1/gems/puppet-3.6.2/lib/puppet/type.rb:1940:in `block in eachautorequire'
     # /var/lib/gems/1.9.1/gems/puppet-3.6.2/lib/puppet/type.rb:1939:in `each'
     # /var/lib/gems/1.9.1/gems/puppet-3.6.2/lib/puppet/type.rb:1939:in `eachautorequire'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:260:in `relationship_refs'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:281:in `block (2 levels) in precedes?'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:279:in `each'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:279:in `block in precedes?'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:278:in `each'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:278:in `precedes?'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:204:in `block in check_befores'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:203:in `each'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:203:in `check_befores'
     # /home/pasquier-s/.bundler/ruby/1.9.1/rspec-puppet-369d729a36ee/lib/rspec-puppet/matchers/create_generic.rb:99:in `matches?'
     # ./spec/classes/grafana_spec.rb:46:in `block (5 levels) in <top (required)>'
```

The last PR on puppet-rspec (https://github.com/rodjek/rspec-puppet/pull/261) deals with improving the dependency detection. So I decided to use puppet-rspec v2.2.0 instead of master and all tests pass again. I don't know where is the issue though...
